[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --no-input"
]

[start]
cmd = "gunicorn hrms.wsgi --bind 0.0.0.0:$PORT --workers 2"
